---
title: "heat"
output: html_document
date: "2025-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}

library(readxl)
library(dplyr)
library(pheatmap)

# 讀取資料
df <- read_excel("C:/Users/mahler/Desktop/Figure 1.xlsx", sheet = "F1C_Heatmap_6")

# 分組欄位
n_cols <- paste0("N", 1:12, "_6")
s_cols <- paste0("S", 1:12, "_6")
ea_cols <- paste0("EA", 1:12, "_6")

# 三組平均
df_avg <- df %>%
  mutate(
    Normal_6 = rowMeans(select(., all_of(n_cols))),
    Sham_6 = rowMeans(select(., all_of(s_cols))),
    EA_6 = rowMeans(select(., all_of(ea_cols)))
  ) %>%
  select(Sample, Normal_6, Sham_6, EA_6) %>%
  tibble::column_to_rownames("Sample")

# Top 20 rowMeans 降冪
df_top20 <- df_avg %>%
  mutate(row_mean = rowMeans(.)) %>%
  arrange(desc(row_mean)) %>%
  select(-row_mean) %>%
  head(20)

# Z-log2 normalization
df_log2 <- log2(df_top20 + 1e-6)
df_scaled <- t(scale(t(df_log2)))

# 製作 rownames 斜體格式
italic_labels <- paste0("italic('", rownames(df_scaled), "')")

# 註解與色碼
annotation_col <- data.frame(Group = c("Normal_6", "Sham_6", "EA_6"))
rownames(annotation_col) <- colnames(df_scaled)
ann_colors <- list(Group = c(Normal_6 = "navy", Sham_6 = "red", EA_6 = "forestgreen"))

# 畫圖（斜體菌名 + 空白標題）
pheatmap(df_scaled,
         cluster_rows=T,
         cluster_cols=F,
         scale="row",
         border_color="grey",
         fontsize_row =7,
         color = colorRampPalette(rev(c("#B87333","white","blue")))(200),
         clustering_method = "average",
         clustering_distance_rows = "correlation",
         angle_col=90,
         fontsize_col =9,
         annotation_col = annotation_col,
         annotation_colors = ann_colors) 




```



```{r pressure, echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
